name: Build and Publish Add-on

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push add-on
        uses: docker/build-push-action@v5
        with:
          context: ./addons/home-secrets
          file: ./addons/home-secrets/Dockerfile
          platforms: |
            ${{ matrix.arch == 'aarch64' && 'linux/arm64' || '' }}
            ${{ matrix.arch == 'amd64' && 'linux/amd64' || '' }}
            ${{ matrix.arch == 'armv7' && 'linux/arm/v7' || '' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-addon-home-secrets:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.arch }}-addon-home-secrets:latest
          build-args: |
            BUILD_FROM=${{ matrix.arch == 'aarch64' && 'ghcr.io/hassio-addons/base:17.1.0' || matrix.arch == 'amd64' && 'ghcr.io/hassio-addons/base:17.1.0' || 'ghcr.io/hassio-addons/base:17.1.0' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from config
        id: version
        run: |
          VERSION=$(grep '^version:' addons/home-secrets/config.yaml | sed 's/version: *"\([^"]*\)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag version images
        run: |
          for arch in aarch64 amd64 armv7; do
            docker buildx imagetools create \
              --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${arch}-addon-home-secrets:${{ steps.version.outputs.version }} \
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/${arch}-addon-home-secrets:${{ github.sha }}
          done